channels:
- conda-forge
dependencies:
- python=3.11.2
- pip<=22.3.1
- pip:
  - mlflow==3.1.0
  - cloudpickle==3.1.1
  - numpy==1.26.2
  - psutil==5.9.6
  - scikit-learn==1.3.2
  - scipy==1.11.4
name: mlflow-env
